services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Plenta\ContaoCountUpBundle\:
        resource: ../../../ContaoCountUpBundle/*
        exclude: ../../../ContaoCountUpBundle/{Entity,Migrations,Resources,Tests}

    Plenta\ContaoCountUpBundle\Controller\Contao\ContentElement\CountUpElementController:
        tags:
            -   name: contao.content_element
                category: texts
                template: ce_plenta_countup
                type: plenta_countup

    Plenta\ContaoCountUpBundle\EventListener\Contao\DataContainer\CountUpListener:
        public: true
        tags:
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValue.save', method: 'onValueSaveCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValueStart.save', method: 'onValueSaveCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValue.load', method: 'onValueLoadCallback' }
            - { name: 'contao.callback', table: 'tl_content', target: 'fields.plentaCountUpValueStart.load', method: 'onValueLoadCallback' }